### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by axen1** [aleksi-kangas/ets2-lane-detection#1]
Hi, can you please post it as an exe.

**Comment by aleksi-kangas** [comment]
Hi,

A release .exe will come at some point, but please do not hold your breath waiting for that.
I am planning to reorganize dependency management (mainly vcpkg related stuff) and to implement UFLD V2 in the (hopefully) near future. Setting up a proper GitHub workflow is also mandatory. However, I'm a bit busy at the moment, so unfortunately no guarantees for that. I'll close this issue, once the necessary steps have been taken and a release version is up.

**Comment by aleksi-kangas** [comment]
An experimental release version v0.0.1 is up. Please keep in mind that all features are subject to change and there may be bugs.
